//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalServicesHistoryInformation
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ApprovalServiceId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ApplicationStatus { get; set; }
        public Nullable<int> ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public string Reason { get; set; }
        public string Comments { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> HeldInRelationId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> VersionId { get; set; }
        public string SemesterNo { get; set; }
        public Nullable<int> CourseHistoryId { get; set; }
        public Nullable<decimal> AttendancePercentage { get; set; }
        public Nullable<int> Attribute1 { get; set; }
        public Nullable<int> Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
