//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateRangeSetupInformation
    {
        public int Id { get; set; }
        public Nullable<int> HeldInId { get; set; }
        public Nullable<int> HeldInRelationId { get; set; }
        public Nullable<int> AcacalId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> DateRangeActivityTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Attribute1 { get; set; }
        public Nullable<int> Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
