//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Code { get; set; }
        public Nullable<int> DeptID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string Remarks { get; set; }
        public string History { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<int> Status { get; set; }
        public string Program { get; set; }
        public string Designation { get; set; }
        public string LibraryCardNo { get; set; }
        public string MIUEmployeeID { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<int> TeacherTypeId { get; set; }
        public Nullable<int> HallInfoId { get; set; }
    }
}
