//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamMarkDateRangeSetup
    {
        public int Id { get; set; }
        public Nullable<int> AcacalSectionId { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<System.DateTime> CAStartDate { get; set; }
        public Nullable<System.DateTime> CAStartTime { get; set; }
        public Nullable<System.DateTime> CAEndDate { get; set; }
        public Nullable<System.DateTime> CAEndTime { get; set; }
        public Nullable<System.DateTime> FinalStartDate { get; set; }
        public Nullable<System.DateTime> FinalStartTime { get; set; }
        public Nullable<System.DateTime> FinalEndDate { get; set; }
        public Nullable<System.DateTime> FinalEndTime { get; set; }
        public Nullable<System.DateTime> CourseTeacherSubmissionDate { get; set; }
        public Nullable<System.DateTime> InternalExaminerSubmissionDate { get; set; }
        public Nullable<System.DateTime> TabulatorSubmissionDate { get; set; }
        public Nullable<System.DateTime> ThirdExaminerSubmissionDate { get; set; }
        public string Remarks { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Attribute1 { get; set; }
        public Nullable<int> Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ResultPublishedDate { get; set; }
    }
}
