//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminerSetupStudentWise
    {
        public int ExaminerSetupStudentWiseId { get; set; }
        public int AcaCalSectionId { get; set; }
        public int StudentCourseHistoryId { get; set; }
        public int ExamSetupDetailId { get; set; }
        public int FirstExaminer { get; set; }
        public Nullable<int> SecondExaminer { get; set; }
        public Nullable<int> ThirdExaminer { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
