//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseHistory
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> CalCourseProgNodeID { get; set; }
        public Nullable<int> AcaCalSectionID { get; set; }
        public Nullable<int> HeldInRelationId { get; set; }
        public Nullable<int> RetakeNo { get; set; }
        public Nullable<decimal> ObtainedTotalMarks { get; set; }
        public Nullable<decimal> ObtainedGPA { get; set; }
        public string ObtainedGrade { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> CourseStatusID { get; set; }
        public Nullable<System.DateTime> CourseStatusDate { get; set; }
        public Nullable<int> AcaCalID { get; set; }
        public int CourseID { get; set; }
        public int VersionID { get; set; }
        public decimal CourseCredit { get; set; }
        public Nullable<decimal> CompletedCredit { get; set; }
        public Nullable<int> Node_CourseID { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<bool> IsMultipleACUSpan { get; set; }
        public Nullable<bool> IsConsiderGPA { get; set; }
        public Nullable<int> CourseWavTransfrID { get; set; }
        public Nullable<int> SemesterNo { get; set; }
        public Nullable<int> YearNo { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public Nullable<int> EqCourseHistoryId { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Remark { get; set; }
    }
}
